resolver: lts-13.12

packages:
- .

extra-deps:
  - vendor/bson-generic
  - vendor/mongoDB-migration
  - persistent-mongoDB-2.8.0
  - pwstore-fast-2.4.4
  - pretty-terminal-0.1.0.0
  - ginger-0.8.1.0
  - HaskellNet-SSL-0.3.4.1
  - http-api-data-0.3.10
  - mime-mail-0.5.0
  - github: jtdaugherty/HaskellNet
    commit: "2c3da32"
  - text-replace-0.0.0.4

extra-package-dbs: []
